### ISSUE TITLE
As a  good practice don't upload the whole env to github just a requirements.txt

### ISSUE THREAD

**Issue by AroraShreshth** [drDrozio/Django#1]
I just noticed you have uploaded your whole virtual env to the github repo which can cause problems while maintaining this repo, create a requirements.txt file for anyone trying to replicate your env and don't forget to add a .gitignore file that would be necessary for django.

Happy Coding 👨🏻‍💻

**Comment by drDrozio** [comment]
Thanks kasper for pointing it out. I did know about this though xD. I uploaded the env file by mistake since it was in the same folder. Will keep it in mind next time :D Thanks!
